sudo: false
language: python

python:
  - 3.6

cache:
  - pip

before_install:
  - pip install -U pip

install:
  - pip install -U .[reco]
  - pip install -U -r requirements.txt

script:
    - make test
